### ISSUE TITLE
I can not create the application

### ISSUE THREAD

**Issue by buho** [FenixEdu/fenixedu.github.io#40]
Hi.

I'm trying to use the initilization tool located at https://start.fenixedu.org/webapp to generate the fenixedu-academic, but it doesn't work for me.

I can't expand the "Fenix Edu Maven Version" and "Bennu Version" combo boxes. There are no items to select from.

I was trying to use the manual aproach using the maven archetype with no success.

I'm working on a Windows 10 (64Bits) machine. I will apreciate your help.

Thank you very much.

**Comment by sergiofbsilva** [comment]
Hello,

Sorry for our late response to this issue.

This github project only serves our page at [FenixEdu.org](https://fenixedu.org).

It should be working now, though.

Thank you.
