### ISSUE TITLE
Add repository in /etc/maven/settings.xml for finding fenix-webapp-archetype-2.0.0.jar

### ISSUE THREAD

**Issue by shemgp** [FenixEdu/fenixedu.github.io#41]
Running:
```bash
mvn archetype:generate -DarchetypeGroupId=org.fenixedu -DarchetypeArtifactId=fenix-webapp-archetype -DarchetypeVersion=2.0.0 -DarchetypeRepository=https://fenix-ashes.ist.utl.pt/nexus/content/groups/fenix-ashes-maven-repository
```
results in an error where `fenix-webapp-archetype-2.0.0.jar` and `fenix-webapp-archetype-2.0.0.pom` can't be found.

The solution is to add:
```xml
    <profile>
      <id>jdk-1.8</id>

      <activation>
        <jdk>1.8</jdk>
      </activation>

      <repositories>
        <repository>
          <id>jdk18</id>
          <name>Fenix</name>
          <url>https://repo.fenixedu.org/simple/fenix-ashes-releases/</url>
          <layout>default</layout>
          <snapshotPolicy>always</snapshotPolicy>
        </repository>
      </repositories>
    </profile>
```
to `/etc/maven/settings.xml`.

Hope this helps somebody.

**Comment by sergiofbsilva** [comment]
Hello,
This github project only serves our page at [FenixEdu.org](https://fenixedu.org)

You should be able to run it following [this](https://confluence.fenixedu.org/display/FENIXEDU/Getting+Started) guide.

Please create an issue with the detailed problem in our issue tracking system, [JIRA](https://jira.fenixedu.org/) if you encounter any problem.

Closing this for now.
