### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by tahirhassaan** [FenixEdu/fenixedu.github.io#44]
i am facing the problem in step 4, error message is here, with hope to have reply soon

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.0.1:generate (default-cli) on project standalone-pom: The desired archetype does not exist (org.fenixedu:fenix-webapp-archetype:2.0.0) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by fsheik** [comment]
@tahirhassaan Did you figure this out?

**Comment by sergiofbsilva** [comment]
Hello,

Can you please follow this up on Jira ?
There is a similar issue [here](https://jira.fenixedu.org/browse/ACDM-1389)

Thanks.
